### ISSUE TITLE
Data retrieval and basic analysis

### ISSUE THREAD

**Issue by mkramer6** [fdac18/FlightCost#15]
GetFlightData(dep, arrive)
GetFlightDataDate(dep, arrive, date) -> variable per year, quarter, and overall
AverageFlightCostPerPerson(dep, arrive, data) -> calls or uses response
YearlyTrend
Surrounding airports (current) -  FUTURE SPRINT

**Comment by caiwjohn** [comment]
Partitioned into individual issues and assigned.
